### PR TITLE
No newlines when copying

### LINKED ISSUE #249: Do not create newlines in long lines when copying
**Describe the bug**
Aminal inserts newlines in all copied data, even when there are none

**To Reproduce**
1. Create a multi line file (e.g. SSH public key)
2. Read it in the terminal (e.g. via cat)
3. Select it so it copies
4. Paste it into a different editor (e.g. sublime)
5. Notice that it has inserted newlines into the long line

**Expected behavior**
No newlines added.

Putty gets this right if you do the exact same process.

### PR DESCRIPTION
**Pull request by rrrooommmaaa**
## Description

Aminal should not insert newlines in copied data if they were not printed to the terminal (i.e. wrapped automatically)

Fixes #249 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Created a file with lines larger then console width, then selected the text with mouse

**Test Configuration**:
* OS: Ubuntu
* OS version: 18.04
* Go version: 1.11

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: buffer/line.go [hunk 1]
```diff
@@ -6,12 +6,14 @@ import (
 
 type Line struct {
 	wrapped bool // whether line was wrapped onto from the previous one
+	nobreak bool // true if no line break at the beginning of the line
```
Comment (mjs) [inline buffer/line.go]: It would be clearer to read the changes in this PR if the sense of this was changed so this was just `break`.
`setNoBreak(true)` is harder to think about than `setBreak(false)`

Comment (rrrooommmaaa) [reply buffer/line.go]: well, setBreak sounds weird to me. Need to specify what kind of break, maybe )
