### PR TITLE
Add another workaround for darwin SDL blank window bug

### LINKED ISSUE #108: Mac OS: black window after start
**Describe the bug**
On my Mac OS after start aminal black window is appeared, nothing happens during key press, mouse hover etc... The workaround to get content at window to perform resize of the window, after it working as expected.... it seems appeared issue with init or init render at OpenGL stuck 

**To Reproduce**
1. Run aminal at macOs
2. Look at the window 

**Expected behavior**
Window with terminal appeared

**Environment (please complete the following information):**
 - OS + Version: macOS 10.1.4.1
 - Go Version: go1.11.2
 - Shell: fish

### PR DESCRIPTION
**Pull request by vkravets**
# Pull Request Template

## Description

As for me it's much better then moving window at one pixel

(Based on the https://github.com/Noofbiz/glfwMojaveFix)

Fixes #108

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Run aminal look at window content it should be appeared istead of black screen

**Test Configuration**:
* OS: macOS
* OS version: 10.14.1
* Go version: 1.11.2

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by vkravets** [comment]
Unfortunately on the CircleCI there is no binaries to build native code which injected to go source at build machine... Locally everything is ok, and also from 10.14 `NSOpenGLContext` marked as deprecated... but it's only warning... I hope when it will be removed such workaround will not needed

If you want to leave fix with moving I would like to propose to move +1 pixel and return to initial position move again to -1... To make sure that the position is initial what we expected

**Comment by vkravets** [comment]
It seems need problem in the build machine https://stackoverflow.com/questions/11912878/gcc-error-gcc-error-trying-to-exec-cc1-execvp-no-such-file-or-directory/45403093

File: gui/gui.go [hunk 1]
```diff
@@ -18,6 +19,19 @@ import (
 	"go.uber.org/zap"
 )
 
+/*
+#cgo CFLAGS: -x objective-c
```
Comment (vkravets) [inline gui/gui.go]: I think we can also execute this code only if system is darwin... I'm not aware how it can be done correctly in go thus... let me know I've fixed

**Comment by liamg** [comment]
That looks good, nice one 👍

**Comment by vkravets** [comment]
Found how to resolve issue with "build for darwin only"... See latest commit, with all compiler configuration and files for different oses

**Comment by vkravets** [comment]
Ohhh... so quickly ))) Thanks!

**Comment by vkravets** [comment]
@liamg-form3 it will be executed only at first swap buffers operation since is used global variable (counter) and we check if it have been done 2 times... Thus it will be executed only before first swap buffer

**Comment by vkravets** [comment]
@liamg-form3 thank to pointing to build configuration, I've don't see it when look at the code =))) I'm always ignore comment when look at the code ( Thus I've miss that... But google helps me how to do that.

BTW go it's something new for me... and as Java developer I can say that it's very similar of combination:
- Java
- Pascal
- C

And have full power of c++, great language as for me )
